spring:
  application:
    name: sapper-game

logging:
  level:
    org.zalando.logbook: TRACE
    ru.catr.game.sapper.service.turn: DEBUG

logbook:
  include:
    - /api/**

game:
  # конфиг валидации игрового поля
  validate:
    # минимальное количество мин
    min-mines-count: 1
    # минимальная высота поля
    min-height: 2
    # максимальная высота поля
    max-height: 50
    # минимальная ширина поля
    min-width: 2
    # максимальная ширина поля
    max-width: 50

springdoc:
  swagger-ui:
    url: /api.yml